mutation createTemplate(
  $workspaceId: String!
  $workspaceNamespace: String!
  $templateName: String!
  $environmentList: [EnvironmentListListItemInput!]!
  $templateId: String = "template-"
  $deleteAfterCreation: String
  $descriptionTemplate: String!
  $stopAfterInactivity: String
  $deleteAfterInactivity: String
  $allowPublicExposure: Boolean
  $nodeSelector: JSON
) {
  createdTemplate: createCrownlabsPolitoItV1alpha2NamespacedTemplate(
    namespace: $workspaceNamespace
    itPolitoCrownlabsV1alpha2TemplateInput: {
      kind: "Template"
      apiVersion: "crownlabs.polito.it/v1alpha2"
      spec: {
        prettyName: $templateName
        description: $descriptionTemplate
        cleanup: {
          deleteAfterCreation: $deleteAfterCreation
          stopAfterInactivity: $stopAfterInactivity
          deleteAfterInactivity: $deleteAfterInactivity
        }
        environmentList: $environmentList
        allowPublicExposure: $allowPublicExposure
        nodeSelector: $nodeSelector
        workspaceCrownlabsPolitoItWorkspaceRef: { name: $workspaceId }
      }
      metadata: { generateName: $templateId, namespace: $workspaceNamespace }
    }
  ) {
    spec {
      prettyName
      description
      cleanup {
        deleteAfterCreation
        stopAfterInactivity
        deleteAfterInactivity
      }
      allowPublicExposure
      nodeSelector
      environmentList {
        name
        guiEnabled
        persistent
        resources {
          cpu
          disk
          memory
          reservedCPUPercentage
        }
      }
    }
    metadata {
      name
      namespace
    }
  }
}
